# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_contact", models.CharField(blank=True, max_length=255)),
                ("referring_party", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("new", "New"), ("screening", "Screening"), ("matched", "Matched"), ("scheduled", "Scheduled"), ("completed", "Completed"), ("closed", "Closed")], default="new", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("clinic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic")),
                ("matched_therapist", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="directory.therapistprofile")),
            ],
        ),
        migrations.AddIndex(model_name="referral", index=models.Index(fields=["clinic"], name="referrals_re_clinic__idx")),
        migrations.AddIndex(model_name="referral", index=models.Index(fields=["status"], name="referrals_re_status__idx")),
    ]
