# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_recurring", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("therapist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="directory.therapistprofile")),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("confirmed", "Confirmed"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("no_show", "No Show")], default="scheduled", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patients.patientprofile")),
                ("therapist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="directory.therapistprofile")),
            ],
        ),
        migrations.AddIndex(model_name="availabilityslot", index=models.Index(fields=["therapist"], name="appointment_avail_therapist_idx")),
        migrations.AddIndex(model_name="availabilityslot", index=models.Index(fields=["day_of_week"], name="appointment_avail_day_idx")),
        migrations.AddIndex(model_name="appointment", index=models.Index(fields=["therapist"], name="appointment_appt_therapist_idx")),
        migrations.AddIndex(model_name="appointment", index=models.Index(fields=["patient"], name="appointment_appt_patient_idx")),
        migrations.AddIndex(model_name="appointment", index=models.Index(fields=["start_at"], name="appointment_appt_start_idx")),
    ]
