# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.TextField(blank=True)),
                ("specialties", models.JSONField(default=list)),
                ("credentials", models.CharField(blank=True, max_length=255)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("is_accepting", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clinic", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="therapist_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(model_name="therapistprofile", index=models.Index(fields=["is_accepting"], name="directory_th_is_acce_idx")),
        migrations.AddIndex(model_name="therapistprofile", index=models.Index(fields=["clinic"], name="directory_th_clinic__idx")),
    ]
