# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("view", "View"), ("login", "Login"), ("logout", "Logout")], max_length=20)),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(model_name="auditevent", index=models.Index(fields=["created_at"], name="audit_audit_created_idx")),
        migrations.AddIndex(model_name="auditevent", index=models.Index(fields=["user"], name="audit_audit_user_id_idx")),
        migrations.AddIndex(model_name="auditevent", index=models.Index(fields=["resource_type"], name="audit_audit_resourc_idx")),
    ]
